spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_schema?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 177418
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minidle: 5
    maxActive: 20 #最大访问数
    maxWait: 60000 #最长等待时间
    filters: stat, wall, log4j #过滤器
    maxPoolPreparedStatementPerConnectionSize: 20 #每个连接池准备语句数
    useGlobalDataSourceState: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
